services:
  api:
    build: ./API/
    command: sh -c "sleep 10s ; python3 app.py"
    depends_on:
      - mysql

  front:
    build: ./Frontend/
    command: sh -c "sleep 10s ; python3 app.py"
    depends_on:
      - api
    ports:
        - "5000:5000"

  mysql:
    build: ./API/database/
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 'pass'
        MYSQL_DATABASE: 'adminprop'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'pass'
